postgresql:
    # Configure size of the persitant volume used with helm managed chart.
    # This should be commented out if using an external endpoint.
    persistence:
      resourcePolicy: nil
      size: 20Gi
      #existingClaim: data-anchore-engine-postgresql-0

anchoreGlobal:
    # Image used for all anchore engine deployments (excluding enterprise components).
    image: docker.io/anchore/anchore-engine:v0.6.1
    imagePullPolicy: IfNotPresent

anchoreEnterpriseGlobal:
  enabled: true

anchore-feeds-db:
  # Configure size of the persitant volume used with helm managed chart.
  # This should be commented out if using an external endpoint.
  persistence:
    resourcePolicy: nil
    size: 20Gi
    #existingClaim: example-feeds-db-claim