dependencies:
  - name: postgresql
    version: "8.0.0"
    repository: "alias:bitnami"
    condition: postgresql.enabled

  - name: postgresql
    version: "8.0.0"
    repository: "alias:bitnami"
    condition: anchore-feeds-db.enabled,anchoreEnterpriseGlobal.enabled
    alias: anchore-feeds-db

  - name: redis
    version: "6"
    repository: "alias:stable"
    condition: anchore-ui-redis.enabled,anchoreEnterpriseGlobal.enabled
    alias: anchore-ui-redis